---
- name: Hello World!
  hosts: all
 
  tasks:
     
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - name: Install cowsay
    apt: name=cowsay state=installed 
    tags: cowsay

