---
- name: Hello World!
  hosts: all
 
  tasks:
     
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - name: Install ntpdate
    become: true
    apt: name=ntpdate state=installed 
    tags: ntpdate

